### ISSUE TITLE
Spaces between address and Download CSV link, plus Copy icon

### ISSUE THREAD

**Issue by ReacherLTD** [bshuler/blocks-divi-domains-issues#1]
There needs to be a decent space between the address and the Download CSV link. As they are right next to each other, it is very hard to copy/paste and a double click ends up selecting part of the Download CSV text. It would be super nice if a little Copy link (the two pages icon) was a space or two to the right of the address and the Download CSV link a few more spaces to the right of that.

**Comment by bshuler** [comment]
fixed
